# Generated by Django 5.2.5 on 2025-08-25 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('number_of_reviews', models.BigIntegerField(blank=True, null=True)),
                ('number_of_products', models.BigIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='marketplaces/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
