# Generated by Django 5.2.5 on 2025-08-25 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='marketplace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplaces.marketplace'),
            preserve_default=False,
        ),
    ]
