# Generated by Django 5.2.5 on 2025-08-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0003_remove_product_category_product_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplaces/'),
        ),
    ]
