# Generated by Django 5.2.5 on 2025-08-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0004_alter_marketplace_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
